name: PHPStan
on:
    workflow_call:
      inputs:
        shopwareVersion:
          type: string
          required: true
          default: '6.5.6'
        args:
          type: string
          required: true
          default: 'analyse --level max'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHPStan
        uses: docker://aragon999/phpstan-shopware:${{ inputs.shopwareVersion }}
        with:
          args: ${{ inputs.args }}
