name: PHPStan
on:
    workflow_call:
      inputs:
        shopwareVersion:
          type: string
          required: false
          default: '6.5.6'
        args:
          type: string
          default: 'analyse --error-format github --level max .'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: PHPStan
        run: docker run --rm -v $(pwd):/app aragon999/phpstan-shopware:v${{ inputs.shopwareVersion }} ${{ inputs.args }}
