# This workflow is meant to be used to build plugin compatible with composer without store

on:
  workflow_call:
    inputs:
      PLUGIN_NAME:
        description: 'Your plugin name'
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

env:
  PLUGIN_NAME: ${{ inputs.PLUGIN_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pluginDeploy:
    container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build & create zip
        run: |
          if test -f "./src/Resources/app/administration/package.json"; then
              npm install --prefix "./src/Resources/app/administration/"
          fi

          if test -f "./src/Resources/app/storefront/package.json"; then
              npm install --prefix "./src/Resources/app/storefront/"
          fi

          if test -f "./src/Resources/app/package.json"; then
              npm install --prefix "./src/Resources/app/"
          fi

          cp -r "./" "/plugins/${PLUGIN_NAME}"

          start-mysql
          pack-plugin "${PLUGIN_NAME}"

      - name: Upload Artefact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: ${{ env.PLUGIN_NAME }}.zip

      - name: Unzip
        run: |
          unzip -o -q "${PLUGIN_NAME}.zip" -d ./toDeploy
          find ./ -maxdepth 1 ! -name "toDeploy" ! -name ".git" ! -name "." ! -name ".." -exec rm -rf {} \;
          mv ./toDeploy/${PLUGIN_NAME}/* ./
          rm -rf ./toDeploy
          rm -rf ./.github

      - name: Get version
        run: |
            echo "PLUGIN_VERSION=$(jq ".version" composer.json -r)" >> $GITHUB_ENV

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ env.PLUGIN_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup git config
        if: steps.checkTag.outputs.exists != 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        if: steps.checkTag.outputs.exists != 'true'
        run: |
          git add -f *
          git commit -m "chore: Build release"
          echo "GITHUB_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          git tag ${PLUGIN_VERSION}
          git push origin ${PLUGIN_VERSION}
#          git push -f origin HEAD:release/${PLUGIN_VERSION}

      - name: Bump version and push tag
        if: steps.checkTag.outputs.exists != 'true'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          tag_prefix: ""
          github_token: ${{ env.GITHUB_TOKEN }}
          custom_tag: ${{ env.PLUGIN_VERSION }}
          commit_sha: ${{ env.GITHUB_SHA }}

      - name: Remove release-branch
        if: steps.checkTag.outputs.exists != 'true'
        run: |
          git push origin --delete release/${PLUGIN_VERSION}

      - name: Create a GitHub release
        if: steps.checkTag.outputs.exists != 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_version }}
          name: Release ${{ steps.tag_version.outputs.new_version }}
          body: ${{ steps.tag_version.outputs.changelog }}